#!/usr/bin/env bash
set -euo pipefail

function _mkinitcpio {
    # mkinitcpio
    sed -i -e 's~^BINARIES=()$~BINARIES=(/usr/bin/btrfs)~g' /etc/mkinitcpio.conf
    sed -i -e 's~^HOOKS=(.*)$~HOOKS=(base systemd autodetect keyboard sd-vconsole modconf block sd-encrypt filesystems fsck)~g' /etc/mkinitcpio.conf
    # sd-vconsle needs vconsole.conf file
    echo "KEYMAP=en" > /etc/vconsole.conf
    mkinitcpio -p linux
}

function _grub {
    local -r model_disk1=$1
    local -r model_disk2=$2
    local -r device_disk1="$(find_disk_dev "$model_disk1")"
    local -r uuid_disk1="$(find_uuid_dev "${device_disk1}3")"
    local -r device_disk2="$(find_disk_dev "$model_disk2")"
    local -r uuid_disk2="$(find_uuid_dev "${device_disk2}1")"

    # Grub
    sed -i -e "s~^GRUB_CMDLINE_LINUX_DEFAULT=.*$~GRUB_CMDLINE_LINUX_DEFAULT=\"rd.luks.name=$uuid_disk1=cryptdisk1 rd.luks.name=$uuid_disk2=cryptdisk2 quiet\"~g" /etc/default/grub
    grub-install --target=i386-pc "/dev/$device_disk1"
    grub-mkconfig -o /boot/grub/grub.cfg
}

source "/root/systall/distributions/common/devices"
source "/root/systall/distributions/common/user"
source "/root/systall/distributions/arch/firstboot"

create_firstboot "/root/systall/profiles/pc/firstboot"
_mkinitcpio
_grub "M4-CT128M4SSD2" "ST9500325AS"

echo "Type the root password"
passwd root

# Create user
echo "Creating a new user, please type type the name:"
read username
create_user "$username"
usergroups=($(cat "/root/systall/data/pc/groups"))
add_user_groups "$username" usergroups

# Set preferences in firtsboot script
echo "Select a timezone"
read timezone
sed -i -e "s~###TIMEZONE###~$timezone~g" "/root/systall/profiles/pc/firstboot"

exit
