#!/usr/bin/env bash
set -euo pipefail

function find_disk_dev {
    local model=$1

    if [[ $(lsblk -o kname,model | grep "$model" | wc -l) != 1 ]]; then
        echo 'could not identify an unique disk'
        exit 1
    fi

    local dev=$(lsblk -o kname,model | awk "/$model/"'{print $1}')

    echo $dev
}

function find_uuid_dev {
    local device=$1

    if ! blkid "/dev/$device" > /dev/null; then
        echo 'could not identify an device'
        exit 1
    fi

    local uuid=$(blkid -o export "/dev/$device" | grep "^UUID=" | sed -e 's~^UUID=~~')

    echo $uuid
}

function find_uuid_disk {
    local model=$1
    local device=$2

    find_uuid_dev "$(find_disk_dev "$model")$device"
}
