#!/usr/bin/env bash
set -euo pipefail

function _prepare_disks {
    local -r cpath=$1
    local -r model=$2
    local -r device="/dev/$(find_disk_dev "$model")"

    echo "Running fdisk"
    sfdisk "$device" < "$cpath/data/laptop/sda.out"
    echo "Preparing boot partition"
    mkfs.fat -F32 "${device}1"
    echo "Make Swap partition"
    mkswap "${device}2"
    echo "Preparing dm-crypt"
    cryptsetup -y -v luksFormat --type luks2 "${device}3"
    cryptsetup --persistent --allow-discards open "${device}3" cryptroot
    mkfs.btrfs -f /dev/mapper/cryptroot
    echo "Preparing rootfs subvolumes"
    mount /dev/mapper/cryptroot /mnt
    btrfs subvolume create /mnt/@
    btrfs subvolume create /mnt/@home
    btrfs subvolume create /mnt/@snapshots
    umount /mnt

    echo "Mount on /mnt"
    mount -o subvol=@ /dev/mapper/cryptroot /mnt
    mkdir /mnt/{boot,home,.snapshots}
    mount "${device}1" /mnt/boot
    mount -o subvol=@home /dev/mapper/cryptroot /mnt/home
    mount -o subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots
    swapon "${device}2"
}

function install_system {
    local -r cpath=$1

    source "$cpath/distributions/arch/install"
    source "$cpath/distributions/arch/config"
    source "$cpath/distributions/common/devices"

    echo "Prepare disks"
    _prepare_disks "$cpath" "Samsung_SSD_850_EVO_250GB"

    echo "Enable multilib"
    enable_multilib_rep

    install_arch "laptop" "/mnt" "$cpath"

    # Create fstab
    genfstab -U "/mnt" >> "/mnt/etc/fstab"

    # Copy data
    cp -r "$cpath" /mnt/root/systall

    # Configure
    arch-chroot "/mnt" "/root/systall/profiles/laptop/chrun"

    umount -R "/mnt"
    swapoff --all
    reboot
}
