#!/usr/bin/env bash
set -euo pipefail

function _prepare_disks {
    local -r cpath=$1
    local -r model=$2
    local -r device="/dev/$(find_disk_dev "$model")"

    echo "Running fdisk"
    sfdisk "$device" < "$cpath/data/asterix/sda.out"
    echo "Preparing boot partition"
    mkfs.fat -F32 "${device}1"
    echo "Make Swap partition"
    mkswap "${device}2"
    echo "Preparing dm-crypt"
    cryptsetup -y -v luksFormat --type luks2 "${device}3"
    cryptsetup --persistent --allow-discards open "${device}3" cryptroot
    mkfs.btrfs -f /dev/mapper/cryptroot
    echo "Preparing rootfs subvolumes"
    mount /dev/mapper/cryptroot /mnt
    btrfs subvolume create /mnt/@
    btrfs subvolume create /mnt/@home
    btrfs subvolume create /mnt/@snapshots
    umount /mnt

    echo "Mount on /mnt"
    mount -o subvol=@ /dev/mapper/cryptroot /mnt
    mkdir /mnt/{boot,home,.snapshots}
    mount "${device}1" /mnt/boot
    mount -o subvol=@home /dev/mapper/cryptroot /mnt/home
    mount -o subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots
    swapon "${device}2"
}

function install_system {
    local -r cpath=$1

    export DEBIAN_FRONTEND=noninteractive
    source "$cpath/distributions/ubuntu/install"
    source "$cpath/distributions/ubuntu/config"
    source "$cpath/distributions/common/devices"

    echo 'Prepare disks'
    _prepare_disks "$cpath" 'KINGSTON SA400S3'

    install_ubuntu '/mnt' 'bionic'

    # Copy data
    cp -r "$cpath" '/mnt/root/systall'

    # mount special devices
    for dev in /dev /dev/pts /proc /sys /run; do
        mount -B "$dev" "/mnt$dev";
    done
    chroot '/mnt' '/root/systall/profiles/asterix/chrun' 'asterix' '/root/systall' 'bionic'

    umount -R '/mnt'
    swapoff --all
    reboot
}
