#!/usr/bin/env bash
set -euo pipefail

function configure {
    local -r hostname=$1
    local -r timezone=$2

    # Set locales
    sed -i -e 's/^# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
    sed -i -e 's/^# es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen
    locale-gen
    cat > /etc/default/locale << EOFL
LANG="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
EOFL
    timedatectl set-timezone "$timezone"
    hostnamectl set-hostname "$hostname"
    timedatectl set-ntp true
    hwclock --systohc
}

function enable_services {
    systemctl enable lightdm.service || true
    systemctl enable NetworkManager || true
    systemctl enable ssh || true
    systemctl enable udisks2.service || true
    systemctl enable org.cups.cupsd.service || true
    systemctl enable docker.service || true
    systemctl enable pcscd.socket || true
    systemctl enable pcscd.service || true
    systemctl enable cups.service || true
}
