#!/usr/bin/env bash
set -euo pipefail

source "/root/systall/distributions/common/devices"
source "/root/systall/distributions/common/user"
source "/root/systall/distributions/common/firstboot"
source "/root/systall/distributions/ubuntu/install"

function _fstab {
    local -r uuid_sda1="$(find_uuid_dev sda1)"
    local -r uuid_sda2="$(find_uuid_dev sda2)"
    local -r uuid_cryptroot="$(find_uuid_dev mapper/cryptdisk1)"

    cp "$cpath/data/obelix/etc/fstab" "/etc/fstab"

    sed -i "s/{{sda1}}/$uuid_sda1/g" '/etc/fstab'
    sed -i "s/{{sda2}}/$uuid_sda2/g" '/etc/fstab'
    sed -i "s/{{cryptroot}}/$uuid_cryptroot/g" '/etc/fstab'
}

function _crypttab {
    local -r uuid1="$1"
    local -r uuid2="$2"

    cat > '/etc/crypttab' <<EOFC
cryptdisk1 UUID=$uuid1 none luks
cryptdisk2 UUID=$uuid2 none luks
EOFC
}

function _grub {
    local -r model=$1
    local -r device="$(find_disk_dev "$model")"

    grub-install "/dev/$device"
    grub-mkconfig -o /boot/grub/grub.cfg
}

function _run {
    local -r profile="$1"
    local -r cpath="$2"
    local -r distribution="$3"

    _fstab
    _crypttab "$(find_uuid_disk 'M4-CT128M4SSD2' '3')" "$(find_uuid_disk 'ST9500325AS' '1')"
    install_ubuntu_repositories "$distribution"
    install_ppas "$profile" "$cpath"
    install_pkgs "$profile" "$cpath"
    _grub 'M4-CT128M4SSD2'

    configure_i3 "/root/systall"
    configure_xorg "/root/systall"

    echo 'Select a timezone'
    read -r timezone
    configure_arch "obelix" "$timezone"
    # Copy netplat NetworkManager configuration
    cp "/root/systall/data/common/etc/netplan/01-network-manager-all.yaml" "/etc/netplan/"
    enable_services

    echo 'Type the root password'
    passwd root

    # Create user
    echo 'Creating a new user, please type type the name:'
    read -r username
    create_user "$username"
    usergroups=($(cat '/root/systall/data/obelix/groups'))
    add_user_groups "$username" usergroups
    rm -rf /root/systall
}

_run "$@"
exit
