#!/usr/bin/env bash
set -euo pipefail

source "/root/systall/distributions/common/config"
source "/root/systall/distributions/common/firstboot"
source "/root/systall/distributions/ubuntu/config"

nvidia-xconfig

remove_firstboot
rm -rf /root/systall
systemctl reboot
